version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/recipes_api"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/recipes_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/local_storage_recipes_api"
    schedule:
      interval: "daily"
